### ISSUE TITLE
Upgrade to Dart Sass

### ISSUE THREAD

**Issue by mvuljevas** [trafilea/nx-shopify#33]
## LibSass Deprecation

Since 26 October 2020 **LibSass** has been deprecated. This means that we ideally need to start working with the latest version of Dart Sass.

[LibSass Deprecation Announcement](https://sass-lang.com/blog/libsass-is-deprecated)

## Motivation

With Dart Sass we're going to be able to use all the improvements that this release has, like the use of **_@use_** instead of **_@import_** and behind the upgrade there's a performance improvement from the code base. 

## Suggested Implementation

Instead of _node-sass_ we should use just _sass_

**Comment by sebastiandg7** [comment]
Closing as  `sass` is already being used

**Comment by mvuljevas** [comment]
Perfect @sebastiandg7!, I've checked and dart sass is correctly working, amazing!
